name: smart_popup
description: "A versatile Flutter alert dialog with lotties, images, animations, countdown timer, Loading and open duration state for buttons etc."
version: 2.0.4
homepage: https://github.com/fazil-kp/smart_popup.git

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_timer_countdown: ^1.0.7
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/lottie/warning.json
    - assets/lottie/success.json
    - assets/lottie/error.json
    - assets/lottie/info.json
    - assets/lottie/delay.json
    - assets/lottie/loading.json
